name: PocketHelpTowny
main: me.PocketIsland.PocketHelpTowny.PocketHelpTowny
version: 1.0
description: >
             Pocket Help Plugin.
commands:
  help:
    description: Displays helpful information about the server