name: SkyWars
main: me.PocketIsland.SkyWars.Core
version: 1.0
depend: [CoreProtect, TabAPI, Vault]
description: >
             Sky Wars plugin.
commands:
  sw:
    description: Sky Wars commands.
  skywars:
    description: Sky Wars commands.
  skywars:
    description: Select a kit!