name: SurvivalGames
main: me.PocketIsland.SurvivalGames.Core
version: 1.0
description: >
             Survival Games Plugin
commands:
  sg:
    description: Buy perks using in-game money!
  hg:
    description: Buy perks using in-game money!