name: Pocketchat
main: me.PocketIsland.pocketchat.Pocketchat
version: 1.0
description: >
             Pocket Chat Plugin.
commands:
  forcechat:
    description: Forces a player to send a message or command.
    usage: /forcechat (Player) (Chat Message|Command)
  nopms:
    description: Toggles receving private messages.
    usage: /nopms
  spy:
    description: Toggles seeing private messages and commands.
    usage: /spy
  silence:
    description: Mutes the entire chat.
    usage: /silence
  m:
    description: Sends a private message
    usage: /<Command>
  msg:
    description: Sends a private message
    usage: /<Command>
  tell:
    description: Sends a private message
    usage: /<Command>
  w:
    description: Sends a private message
    usage: /<Command>
  whisper:
    description: Sends a private message
    usage: /<Command>
  pm:
    description: Sends a private message
    usage: /<Command>
  r:
    description: Sends a private message
    usage: /<Command>
  reply:
    description: Sends a private message
    usage: /<Command>
  helpop:
    description: Requests help from online staff
    usage: /helpop (Chat Message)
  chat:
    description: Plugin Info
    usage: /chat
  d:
    description: Sends a message to donor chat
    usage: /d (Chat Message)
  s:
    description: Sends a message to staff chat
    usage: /s (Chat Message)
  timeout:
    description: Mutes a player from speaking
    usage: /timeout (Player) [Seconds]
  me:
    description: Emotes messages
    usage: /me (Chat Message)
  clearchat:
    description: Clears the chat history
    usage: /clearchat
  mute:
    description: Alt. for /timeout
    usage: /timeout (Player) [Seconds]