name: PocketSpy
main: me.PocketIsland.PocketSpy.Core
version: 1.0
description: >
             Pocket Spy Plugin.
commands:
  manuadd:
    description: Used to move player groups.
  manuaddsub:
    description: Used to do add player subgroups.